version: "3.3"

services:
  postgres:
    restart: always
    build:
      context: .
      dockerfile: postgres/Dockerfile
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: please_db
    ports:
      - "15432:5432"
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
